<?php

// DO NOT EDIT! This file is auto generated by 'Shopware\Core\Framework\Feature'}
namespace Symfony\Component\DependencyInjection\Loader\Configurator;

return static function(ContainerConfigurator $configurator) {
    $configurator->parameters()->set(
        'shopware.features',
        array (
  'FEATURE_NEXT_1797' => false,
  'FEATURE_NEXT_3722' => false,
  'FEATURE_NEXT_5983' => false,
  'FEATURE_NEXT_10286' => false,
  'FEATURE_NEXT_9351' => false,
  'FEATURE_NEXT_10058' => false,
  'FEATURE_NEXT_10077' => false,
)
    );
};