<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEAblh28\srcShopware_Production_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEAblh28/srcShopware_Production_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerEAblh28.legacy');

    return;
}

if (!\class_exists(srcShopware_Production_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerEAblh28\srcShopware_Production_KernelDevDebugContainer::class, srcShopware_Production_KernelDevDebugContainer::class, false);
}

return new \ContainerEAblh28\srcShopware_Production_KernelDevDebugContainer([
    'container.build_hash' => 'EAblh28',
    'container.build_id' => 'a551b01a',
    'container.build_time' => 1602249301,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEAblh28');
